# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('finish_time', models.DateField(blank=True, null=True)),
                ('invited_users', models.TextField(default='')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('DELAYED', 'Delayed'), ('IN_PROGRESS', 'In progress')], default='IN_PROGRESS', max_length=11)),
                ('event_header', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event_header', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('finish_time', models.DateField()),
                ('is_public', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('DELAYED', 'Delayed'), ('IN_PROGRESS', 'In progress')], default='IN_PROGRESS', max_length=11)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('task_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_header', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Task'),
        ),
    ]
