# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='invited_users',
        ),
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
