# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160819_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_public',
        ),
    ]
