# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_task_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finish_time',
            field=models.DateField(null=True),
        ),
    ]
