language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - cp intask/conf_demo.py intask/conf.py
before_script:
  - python manage.py migrate
script:
  - python manage.py test

notifications:
  email: false